CREATE TABLE Employees (
    Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    Department NVARCHAR(50) NOT NULL,
    HireDate DATETIME NOT NULL,
    Salary DECIMAL(18,2) NOT NULL,
    PhoneNumber NVARCHAR(15) NOT NULL
);
